"""Reference-history-based feature derivation.

Faithful port of the AI team's src/predict/predictor.py (inbox/a15/codigo/) —
_add_financial_base_2020_indices_for_inference, _lookup_monthly_values,
_lagged_feature_name, build_inference_panel_from_history, _prepare_user_ipi_history,
_merge_user_ipi_history_into_prices, build_inference_panel_from_user_ipi_history.

Lets a caller who only knows the national IPI value(s) — not the full 16-feature
contract — get a prediction: the other 15 features (6 autoregressive lags, 5 exogenous
lags, 4 calendar) are derived from two bundled reference CSVs (see constants.py) plus,
optionally, the caller's own value(s) merged in at their date(s).

Two bundled reference CSVs are required for this path (see model_loader.py::
reference_data_paths and inbox/a15/manifest.yaml known_issues) — they are historical
reference series refreshed only when the AI team's own data_processing pipeline reruns,
never retrained/regenerated by this plugin.
"""
from __future__ import annotations

import math
from typing import Any

import pandas as pd

from app.plugins.ml15_wine_ipi_price_forecast.constants import (
    AUTOREGRESSIVE_LAGS,
    COMMODITY_LAGS,
    FINANCIAL_RAW_COLUMNS,
    INTL_LAGS,
    SIMPLE_IPI_VALUE_CANDIDATES,
    TARGET_SOURCE_COLUMN,
)
from app.plugins.ml15_wine_ipi_price_forecast.model_loader import reference_data_paths


def _month_start(dates: pd.Series) -> pd.Series:
    return pd.to_datetime(dates, errors="coerce").dt.to_period("M").dt.to_timestamp()


def load_monthly_csv(path: str) -> pd.DataFrame:
    """Load a bundled reference CSV, normalizing 'date' to first-of-month and sorting."""
    df = pd.read_csv(path)
    if "date" not in df.columns:
        raise ValueError(f"Reference file {path} must contain a 'date' column.")
    df = df.copy()
    df["date"] = _month_start(df["date"])
    return df.sort_values("date").reset_index(drop=True)


def reindex_financial_to_base_2020(df_financial: pd.DataFrame) -> pd.DataFrame:
    """Port of _add_financial_base_2020_indices_for_inference.

    Adds a "{col}_idx" column for each of FINANCIAL_RAW_COLUMNS: monthly value / mean of
    that column's 2020 observations * 100 — reproduces the base-2020 reindexing the AI
    team's features.py applies at training time.
    """
    out = df_financial.copy()

    missing = [c for c in FINANCIAL_RAW_COLUMNS if c not in out.columns]
    if missing:
        raise ValueError(
            f"Financial proxy reference file is missing required column(s): {missing}"
        )

    year_2020 = out["date"].dt.year == 2020

    for column in FINANCIAL_RAW_COLUMNS:
        idx_column = f"{column}_idx"
        base_mean = pd.to_numeric(out.loc[year_2020, column], errors="coerce").mean()
        if pd.isna(base_mean) or base_mean == 0:
            raise ValueError(
                f"Cannot compute base-2020 index for '{column}': no valid 2020 "
                "observations in the bundled reference file, or base mean is zero."
            )
        out[idx_column] = pd.to_numeric(out[column], errors="coerce") / base_mean * 100.0

    return out


def _lookup_monthly_values(
    source_df: pd.DataFrame,
    value_column: str,
    lookup_dates: pd.Series,
    source_name: str,
    output_column: str,
    allow_last_available: bool = False,
) -> pd.Series:
    """Port of _lookup_monthly_values (allow_missing is always False here — a value this
    plugin cannot resolve must surface as an explicit error, never a silent NaN feature)."""
    if value_column not in source_df.columns:
        raise ValueError(
            f"Reference file for {source_name} is missing required column '{value_column}'."
        )

    dates = _month_start(pd.Series(lookup_dates).reset_index(drop=True))

    source = source_df[["date", value_column]].copy()
    source["date"] = _month_start(source["date"])
    source[value_column] = pd.to_numeric(source[value_column], errors="coerce")
    source = source.dropna(subset=["date", value_column]).sort_values("date")

    lookup = source.set_index("date")[value_column]
    values = pd.to_numeric(dates.map(lookup), errors="coerce")

    missing = values.isna()
    if missing.any() and allow_last_available and not source.empty:
        for idx in values[missing].index:
            requested_date = pd.Timestamp(dates.loc[idx])
            candidates = source[source["date"] <= requested_date]
            if candidates.empty:
                continue
            values.loc[idx] = float(candidates.iloc[-1][value_column])
        missing = values.isna()

    if missing.any():
        missing_labels = dates.loc[missing].dt.strftime("%Y-%m-%d").unique().tolist()
        raise ValueError(
            f"No se puede derivar la feature '{output_column}': faltan datos de "
            f"{source_name} para {', '.join(missing_labels[:10])}. Aporta la feature "
            "directamente, o un 'ipi_national_current' de una fecha dentro del rango "
            "cubierto por el histórico de referencia."
        )

    return values.reset_index(drop=True)


def _lagged_feature_name(source_column: str, lag: int) -> str:
    """Port of _lagged_feature_name (strips the reindexing suffix from commodity columns)."""
    base = str(source_column)
    for suffix in ("_avg_idx", "_idx", "_avg"):
        if base.endswith(suffix):
            base = base[: -len(suffix)]
            break
    return f"{base}_lag_{int(lag)}"


def merge_user_points_into_prices(
    prices_df: pd.DataFrame, user_points: list[dict[str, Any]],
) -> pd.DataFrame:
    """Port of _merge_user_ipi_history_into_prices.

    Overwrites (or inserts) TARGET_SOURCE_COLUMN in prices_df at each user-supplied
    {"date": ..., "value": ...} point — does not touch the international series.
    """
    out = prices_df.copy()
    out["date"] = _month_start(out["date"])
    out = out.set_index("date").sort_index()

    for point in user_points:
        date = pd.Timestamp(point["date"]).to_period("M").to_timestamp()
        if date not in out.index:
            out.loc[date, :] = pd.NA
        out.loc[date, TARGET_SOURCE_COLUMN] = float(point["value"])

    return out.reset_index().sort_values("date").reset_index(drop=True)


def derive_feature_rows(
    origin_dates: list[pd.Timestamp], prices_df: pd.DataFrame, financial_df: pd.DataFrame,
) -> pd.DataFrame:
    """Port of build_inference_panel_from_history's feature-construction body.

    prices_df/financial_df are expected already loaded (and financial_df already
    reindexed to base-2020, and merged with any user override points the caller wants
    reflected). Returns a DataFrame with 'date' + the 16 FEATURE_COLUMNS, one row per
    origin date, in the SAME order as *origin_dates* (unlike the original
    build_inference_panel_from_history, which re-sorts by date — callers that need the
    original row order, e.g. predict_batch, would otherwise have to re-match rows back to
    input positions by date, which breaks silently if two origin_dates collide).
    """
    out = pd.DataFrame({"date": _month_start(pd.Series(origin_dates))})
    out["month"] = out["date"].dt.month

    out["ipi_national_current"] = _lookup_monthly_values(
        source_df=prices_df, value_column=TARGET_SOURCE_COLUMN, lookup_dates=out["date"],
        source_name="global phytosanitary prices (bundled reference)",
        output_column="ipi_national_current",
    )

    for lag in AUTOREGRESSIVE_LAGS:
        output_col = f"ipi_national_lag_{lag}"
        out[output_col] = _lookup_monthly_values(
            source_df=prices_df, value_column=TARGET_SOURCE_COLUMN,
            lookup_dates=out["date"] - pd.DateOffset(months=lag),
            source_name="global phytosanitary prices (bundled reference)",
            output_column=output_col,
        )

    for source_col, lag in INTL_LAGS.items():
        output_col = f"{source_col}_lag_{lag}"
        out[output_col] = _lookup_monthly_values(
            source_df=prices_df, value_column=source_col,
            lookup_dates=out["date"] - pd.DateOffset(months=lag),
            source_name="global phytosanitary prices (bundled reference)",
            output_column=output_col, allow_last_available=True,
        )

    for source_col, lag in COMMODITY_LAGS.items():
        output_col = _lagged_feature_name(source_col, lag)
        out[output_col] = _lookup_monthly_values(
            source_df=financial_df, value_column=source_col,
            lookup_dates=out["date"] - pd.DateOffset(months=lag),
            source_name="financial proxies (bundled reference)",
            output_column=output_col, allow_last_available=True,
        )

    out["month_sin"] = out["month"].apply(lambda m: math.sin(2.0 * math.pi * m / 12.0))
    out["month_cos"] = out["month"].apply(lambda m: math.cos(2.0 * math.pi * m / 12.0))
    out["quarter"] = out["date"].dt.quarter
    out["is_spring_risk"] = out["month"].isin([4, 5, 6]).astype(int)

    return out.drop(columns=["month"])


def find_simple_ipi_column(columns: list[str]) -> str | None:
    """Port of _prepare_user_ipi_history's value-column resolution priority order."""
    for candidate in SIMPLE_IPI_VALUE_CANDIDATES:
        if candidate in columns:
            return candidate
    return None


def is_simple_history_frame(columns: list[str], feature_columns: list[str]) -> bool:
    """True if *columns* looks like a simple date+IPI-value history — e.g. the AI team's
    own data/input/ipi_history.csv (date,year,month,ipi_national_current) — rather than an
    already-prepared feature panel. predict_batch uses this to decide whether to treat the
    CSV as one independent feature row per line (existing behaviour) or as a history to
    merge and derive lags/exogenous features from, one prediction per row."""
    cols = set(columns)
    if set(feature_columns).issubset(cols):
        return False
    has_date = "date" in cols or {"year", "month"}.issubset(cols)
    return has_date and find_simple_ipi_column(columns) is not None


def resolve_row_date(row: dict) -> pd.Timestamp:
    """Port of _ensure_date_column's per-row date resolution priority: origin_date, then
    date, then year+month."""
    for key in ("origin_date", "date"):
        value = row.get(key)
        if value not in (None, "", "nan"):
            parsed = pd.to_datetime(value, errors="coerce")
            if pd.notna(parsed):
                return pd.Timestamp(parsed).to_period("M").to_timestamp()
    if row.get("year") not in (None, "") and row.get("month") not in (None, ""):
        return pd.Timestamp(year=int(row["year"]), month=int(row["month"]), day=1)
    raise ValueError("No se pudo resolver una fecha para la fila (faltan date/origin_date/year+month).")


def load_reference_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load and prepare the two bundled reference CSVs: (prices_df, financial_df),
    financial_df already reindexed to base-2020. Raises FileNotFoundError if the bundled
    files are missing (see model_loader.py::reference_data_paths)."""
    prices_path, financial_path = reference_data_paths()
    prices_df = load_monthly_csv(prices_path)
    financial_df = reindex_financial_to_base_2020(load_monthly_csv(financial_path))
    return prices_df, financial_df
