data:
  external_data_split:
    test_pct: 20.0
    train_pct: 66.7
    val_pct: 13.3
  fuzzy_processing:
    stats_creation:
    - mean
    - std
    - slope
    - max
    - min
  id_column: cycle_id
  normal_tokens:
  - '0'
  - normal
  - none
  - ok
  - healthy
  - no failure
  - no fallo
  - sin falla
  - sin fallo
  - nofailure
  - nofallo
  - normal operation
  partial_null_max_ratio: 0.1
  sequence_length: 180
  solapamiento_beta: 0.5
  target_column: fault_name
  timestamp_column: timestamp
fuzzy:
  init_alpha: sparse
  lambda_anomaly: 0.7
  n_mf: 5
  n_rules: 24
  normalize_rules: true
  t_norm: product
  temperature: 0.8
  train_membership_params: true
  train_rule_params: true
  use_log_bias: false
lstm:
  bidirectional: true
  dropout: 0.3
  embedding_dim: 32
  hidden_size: 32
  num_layers: 2
seed: 42
training_kwargs:
  batch_size: 256
  dnf_loss:
    alpha_entropy_weight: 0.01
    anomaly_weight: 2.0
    aux_anom_dl_weight: 0.4
    aux_anom_fuzzy_weight: 0.95
    diversity_weight: 0.005
    eps: 1.0e-08
    reduction: mean
    rule_structure_div_weight: 0.02
    rule_usage_balance_weight: 0.04
  grad_clip: 1.0
  lr_rate: 0.00175
  monitor_metric: 0.65*val_anomaly_f1 + 0.25*fuzzy_f1 - 0.05*dead_rules_ratio - 0.05*alpha_entropy_mean
    - 0.05*rule_corr
  num_epochs: 200
  patience: 30
  scheduler:
    T_max: 200
    T_mult: 2
    eta_min: 9.0e-06
    factor: 0.6
    min_lr: 5.0e-05
    patience: 3
    type: cosine
  shuffle_train: false
  warmup_epochs: 20
  weight_decay: 1.0e-05
