"""Preprocessing pipeline for train/test split and scaling."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import joblib
import pandas as pd
from pydantic import BaseModel, ConfigDict, Field, PositiveFloat
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from src.utils.utils import load_dataset


class PreprocessingConfig(BaseModel):
    """Configuration for dataset preprocessing.

    Attributes:
        test_size: Fraction reserved for test split.
        random_state: Random seed.
        split_prefix: Prefix used to save split artifacts.
        physical_columns: Numeric columns to scale.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    test_size: PositiveFloat = 0.2
    random_state: int = 42
    split_prefix: str = "dataset_optimization_cereal_co2"
    physical_columns: tuple[str, ...] = (
        "generated_volume_tons",
        "moisture_pct",
        "process_temperature_c",
    )


@dataclass(frozen=True)
class PreprocessingArtifacts:
    """Paths generated by preprocessing.

    Attributes:
        train_raw_path: Raw training split.
        test_raw_path: Raw test split.
        train_scaled_path: Scaled/encoded training split.
        test_scaled_path: Scaled/encoded test split.
        scaler_path: Serialized scaler artifact.
        scaler_metadata_path: Human-readable scaler metadata with feature ranges.
    """

    train_raw_path: Path
    test_raw_path: Path
    train_scaled_path: Path
    test_scaled_path: Path
    scaler_path: Path
    scaler_metadata_path: Path


RAW_REQUIRED_COLUMNS: tuple[str, ...] = (
    "subproduct_type",
    "season",
    "generated_volume_tons",
    "moisture_pct",
    "process_temperature_c",
    "reuse_strategy",
    "co2_emissions_kg",
    "co2_per_ton",
)

EXPECTED_FEATURE_COLUMNS: tuple[str, ...] = (
    "generated_volume_tons",
    "moisture_pct",
    "process_temperature_c",
    "subproduct_type_Husk",
    "subproduct_type_Straw",
    "subproduct_type_Silo dust",
    "subproduct_type_Bran",
    "season_Rainy",
    "season_Dry",
)

# Final 8-feature vector consumed by the NEAT policy.
# process_temperature_c remains in the preprocessed table for simulator
# consistency and traceability, but is explicitly excluded from this vector.
NEURAL_POLICY_INPUT_COLUMNS: tuple[str, ...] = (
    "generated_volume_tons",
    "moisture_pct",
    "subproduct_type_Husk",
    "subproduct_type_Straw",
    "subproduct_type_Silo dust",
    "subproduct_type_Bran",
    "season_Rainy",
    "season_Dry",
)


def _validate_input_schema(df: pd.DataFrame) -> None:
    """Validate the raw dataset schema.

    Args:
        df: Input dataframe.

    Raises:
        ValueError: If required columns are missing.
    """

    missing = [col for col in RAW_REQUIRED_COLUMNS if col not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns for preprocessing: {missing}")


def _one_hot_and_align(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """One-hot encode categorical columns and align train/test columns.

    Args:
        train_df: Training dataframe.
        test_df: Test dataframe.

    Returns:
        tuple[pd.DataFrame, pd.DataFrame]: Encoded train and test dataframes.
    """

    categorical_columns = ["subproduct_type", "season"]
    train_encoded = pd.get_dummies(train_df, columns=categorical_columns)
    test_encoded = pd.get_dummies(test_df, columns=categorical_columns)

    for column in EXPECTED_FEATURE_COLUMNS:
        if column not in train_encoded.columns and column not in {
            "generated_volume_tons",
            "moisture_pct",
            "process_temperature_c",
        }:
            train_encoded[column] = 0
        if column not in test_encoded.columns and column not in {
            "generated_volume_tons",
            "moisture_pct",
            "process_temperature_c",
        }:
            test_encoded[column] = 0

    train_columns = list(EXPECTED_FEATURE_COLUMNS) + [
        col for col in train_encoded.columns if col not in EXPECTED_FEATURE_COLUMNS
    ]
    train_encoded = train_encoded.reindex(columns=train_columns, fill_value=0)
    test_encoded = test_encoded.reindex(columns=train_columns, fill_value=0)
    return train_encoded, test_encoded


def _scale_physical_columns(
    train_df: pd.DataFrame,
    test_df: pd.DataFrame,
    physical_columns: tuple[str, ...],
) -> tuple[pd.DataFrame, pd.DataFrame, MinMaxScaler]:
    """Fit a MinMax scaler on train and transform train/test.

    Args:
        train_df: Encoded training dataframe.
        test_df: Encoded test dataframe.
        physical_columns: Columns to scale.

    Returns:
        tuple[pd.DataFrame, pd.DataFrame, MinMaxScaler]: Scaled train/test and fitted scaler.
    """

    scaler = MinMaxScaler()
    train_df = train_df.copy()
    test_df = test_df.copy()
    train_df = train_df.copy()
    test_df = test_df.copy()
    train_df[list(physical_columns)] = scaler.fit_transform(train_df[list(physical_columns)])
    test_df[list(physical_columns)] = scaler.transform(test_df[list(physical_columns)])
    train_df = train_df.reindex(columns=list(EXPECTED_FEATURE_COLUMNS) + [
        col for col in train_df.columns if col not in EXPECTED_FEATURE_COLUMNS
    ], fill_value=0)
    test_df = test_df.reindex(columns=list(EXPECTED_FEATURE_COLUMNS) + [
        col for col in test_df.columns if col not in EXPECTED_FEATURE_COLUMNS
    ], fill_value=0)
    return train_df, test_df, scaler


def _build_scaler_metadata(
    scaler: MinMaxScaler,
    physical_columns: tuple[str, ...],
    split_prefix: str,
    random_state: int,
    test_size: float,
) -> dict[str, Any]:
    """Build a JSON-serializable description of scaler ranges and split settings.
    
    Includes explicit denormalization guidance for post-processing workflows.
    """

    ranges = {
        column: {
            "data_min": float(scaler.data_min_[index]),
            "data_max": float(scaler.data_max_[index]),
            "scale": float(scaler.scale_[index]),
            "min_offset": float(scaler.min_[index]),
            "denormalization_formula": f"value_physical = value_normalized / {float(scaler.scale_[index]):.10f} + {float(scaler.data_min_[index])}",
        }
        for index, column in enumerate(physical_columns)
    }
    return {
        "schema_version": 1,
        "split_prefix": split_prefix,
        "random_state": random_state,
        "test_size": test_size,
        "scaled_columns": list(physical_columns),
        "neural_policy_input_columns": list(NEURAL_POLICY_INPUT_COLUMNS),
        "excluded_from_neural_policy_inputs": ["process_temperature_c"],
        "non_scaled_columns": ["subproduct_type_*", "season_*"],
        "note": "One-hot encoded categorical columns (subproduct_type, season) are NOT scaled. Only scaled_columns above are min-max normalized to [0, 1].",
        "ranges": ranges,
        "usage": {
            "forward": "Use scaler.transform() or MinMaxScaler with these ranges to normalize new data.",
            "inverse": "Use scaler.inverse_transform() or apply denormalization_formula manually to recover physical units.",
        },
    }


def run_preprocessing_pipeline(
    input_path: Path,
    output_dir: Path,
    config: PreprocessingConfig,
    logger: logging.Logger,
) -> PreprocessingArtifacts:
    """Run train/test split and scaling preprocessing.

    This pipeline:
    1. Splits the dataset into train (80%) and test (20%) partitions.
    2. One-hot encodes categorical columns (subproduct_type, season).
    3. Applies MinMaxScaler to numeric columns (normalized to [0, 1]).
    4. Saves both raw and scaled splits, plus scaler artifacts with metadata.

    Args:
        input_path: Raw dataset path.
        output_dir: Output directory for split artifacts.
        config: Preprocessing configuration.
        logger: Logger instance.

    Returns:
        PreprocessingArtifacts: Paths of saved artifacts including scaler and metadata.
        
    Artifacts Generated:
        - train_raw.csv, test_raw.csv: Raw splits (no scaling/encoding).
        - train_scaled.csv, test_scaled.csv: Scaled and encoded splits for training.
        - scaler.joblib: Fitted MinMaxScaler object for inverse transformation.
        - scaler_metadata.json: Explicit metadata with denormalization formulas and usage guidance.
        
    Usage for Denormalization:
        1. Load metadata: metadata = load_scaler_metadata(scaler_metadata_path)
        2. Load scaler: scaler = joblib.load(scaler_path)
        3. Denormalize: df_physical = denormalize_columns(df_scaled, scaler, metadata['scaled_columns'])
    """

    df = load_dataset(input_path, logger)
    _validate_input_schema(df)

    train_raw, test_raw = train_test_split(
        df,
        test_size=config.test_size,
        random_state=config.random_state,
        shuffle=True,
    )

    train_raw = train_raw.reset_index(drop=True)
    test_raw = test_raw.reset_index(drop=True)

    train_scaled, test_scaled = _one_hot_and_align(train_raw, test_raw)
    train_scaled, test_scaled, scaler = _scale_physical_columns(
        train_scaled,
        test_scaled,
        config.physical_columns,
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    train_raw_path = output_dir / f"{config.split_prefix}_train_raw.csv"
    test_raw_path = output_dir / f"{config.split_prefix}_test_raw.csv"
    train_scaled_path = output_dir / f"{config.split_prefix}_train_scaled.csv"
    test_scaled_path = output_dir / f"{config.split_prefix}_test_scaled.csv"
    scaler_path = output_dir / f"{config.split_prefix}_scaler.joblib"
    scaler_metadata_path = output_dir / f"{config.split_prefix}_scaler_metadata.json"

    train_raw.to_csv(train_raw_path, index=False)
    test_raw.to_csv(test_raw_path, index=False)
    train_scaled.to_csv(train_scaled_path, index=False)
    test_scaled.to_csv(test_scaled_path, index=False)
    joblib.dump(scaler, scaler_path)
    scaler_metadata = _build_scaler_metadata(
        scaler=scaler,
        physical_columns=config.physical_columns,
        split_prefix=config.split_prefix,
        random_state=config.random_state,
        test_size=config.test_size,
    )
    scaler_metadata_path.write_text(
        json.dumps(scaler_metadata, ensure_ascii=True, indent=2),
        encoding="utf-8",
    )

    logger.info("Preprocessing finished: train_raw=%s, test_raw=%s", train_raw_path, test_raw_path)
    logger.info("Scaled splits saved: train_scaled=%s, test_scaled=%s", train_scaled_path, test_scaled_path)
    logger.info(
        "Temperature handling: process_temperature_c is scaled for simulator/pipeline traceability "
        "but excluded from the 8-feature neural policy input vector=%s",
        NEURAL_POLICY_INPUT_COLUMNS,
    )
    logger.info("Scaler saved to %s", scaler_path)
    logger.info("Scaler metadata saved to %s", scaler_metadata_path)

    return PreprocessingArtifacts(
        train_raw_path=train_raw_path,
        test_raw_path=test_raw_path,
        train_scaled_path=train_scaled_path,
        test_scaled_path=test_scaled_path,
        scaler_path=scaler_path,
        scaler_metadata_path=scaler_metadata_path,
    )
